default_config:

logger:
  default: warning
  logs:
    custom_components.apparent_temperature: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

group:
  test_group:
    entities:
      - sensor.test_temperature
      - sensor.test_humidity

sensor:
  - platform: apparent_temperature
    source: group.test_group

  - platform: template
    sensors:
      test_temperature:
        unit_of_measurement: "°C"
        value_template: "{{ 22.6 }}"
        device_class: temperature

      test_humidity:
#        unit_of_measurement: "%"
        value_template: "{{ 43 }}"
#        device_class: humidity
