---
name: "Python testing"

on:
  push:
  pull_request:
  schedule:
    - cron: "23 3 * * 1"

jobs:
  ruff:
    name: "Ruff"
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout the repository"
          uses: actions/checkout@v4

        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: 'pyproject.toml'
            cache: "pip"

        - name: "Cache pip"
          uses: actions/cache@v4
          with:
            # This path is specific to Ubuntu
            path: ~/.cache/pip
            # Look to see if there is a cache hit for the corresponding requirements file
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
              ${{ runner.os }}-

        - name: "Install dependencies"
          run: |
            python -m pip install --upgrade pip
            # Prefer requirements-dev.txt
            if [ -f requirements-dev.txt ]; then
              scripts/install_requirements requirements-dev.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
            elif [ -f requirements-test.txt ]; then
              scripts/install_requirements requirements-test.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
            elif [ -f requirements.txt ]; then
              scripts/install_requirements requirements.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
            fi

            if [ -d custom_components ]; then
              echo '"""Stub."""' >custom_components/__init__.py
            fi

        - name: "Lint"
          run: python3 -m ruff check .

        - name: "Format"
          run: python3 -m ruff format . --check

  tests:
    name: "Test package"
    needs: ruff
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: "pip"

      - name: "Cache pip"
        uses: actions/cache@v4
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          # Prefer requirements-test.txt
          if [ -f requirements-test.txt ]; then
            scripts/install_requirements requirements-test.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          elif [ -f requirements-dev.txt ]; then
            scripts/install_requirements requirements-dev.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          elif [ -f requirements.txt ]; then
            scripts/install_requirements requirements.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          fi
          pip install pytest-xdist

          if [ -d custom_components ]; then
            echo '"""Stub."""' >custom_components/__init__.py
          fi

      - name: "Install Coveralls"
        run: |
          pip install pytest-xdist coveralls

      - name: "Run tests with pytest & Calculate coverage"
        run: |
          pytest --basetemp=$RUNNER_TEMP --durations=10 -n auto --dist=loadfile -qq -o console_output_style=count -p no:sugar --cov --cov-report=
          ./scripts/check_dirty

      - name: "Send coverage to Coveralls"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
